Repository Negative-Games/Framework, pull requests merged in 2022-04, with the labels that each got.

#65 Fix command permissions for execution
  src/main/java/games/negative/framework/command/Command.java
  src/main/java/games/negative/framework/command/SubCommand.java
Labels: bug

#67 Created FloodgateMenu.java
  pom.xml
  src/main/java/games/negative/framework/gui/floodgate/FloodgateMenu.java
Labels: enhancement, awaiting testing

#71 Add Repository interface
  src/main/java/games/negative/framework/repository/Repository.java
Labels: enhancement

#72 Added Command Caching
  src/main/java/games/negative/framework/BasePlugin.java
  src/main/java/games/negative/framework/command/repository/CommandRepository.java
  src/main/java/games/negative/framework/command/repository/FrameworkCommandRepository.java
Labels: enhancement

#75 Update README.md
  README.md
Labels: documentation

#77 Create issue-project.yml
  .github/workflow/issue-project.yml
Labels: type: documentation, priority: low
